#!/bin/sh

SANITIZED_VERSION=$(echo "$CI_COMMIT_TAG" | egrep -ox '[0-9]+\.[0-9]+\.[0-9]+.*')

if [ -z "$SANITIZED_VERSION" ]; then
  echo "Invalid version format \"$CI_COMMIT_TAG\""
  exit 1
fi

ANNOTATION=$(git tag $CI_COMMIT_TAG -l --format='%(contents:body)' | tr -d '[[:space:]]')
if [ -z "$ANNOTATION" ]; then
  echo "Tag should by annotated"
  exit 1
fi

CHANGELOG_EXPECTED="prometheus-logstash-exporter ($CI_COMMIT_TAG)"
CHANGELOG_FOUND=$(head -n1 debian/changelog | fgrep -o "$CHANGELOG_EXPECTED")

if [ "$CHANGELOG_FOUND" != "$CHANGELOG_EXPECTED" ]; then
  echo "Version $CHANGELOG_EXPECTED expected"
  echo
  echo "Found $(head -n1 debian/changelog)"
  exit 1
fi

exit 0
